apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
spec:
  type: LoadBalancer
  selector: 
    app: pythonapp
  ports:
    - port: 8080
      targetPort: 5000
      nodePort: 31200
